version: '3'

tasks:
  setup:
    desc: Set up the development environment
    cmds:
      - cargo fetch

  run:
    desc: Run the MCP server
    cmds:
      - cargo run

  test:
    desc: Run tests
    cmds:
      - cargo test

  lint:
    desc: Run clippy lints
    cmds:
      - cargo clippy -- -D warnings

  format:
    desc: Format code
    cmds:
      - cargo fmt

  check:
    desc: Run all pre-commit checks
    cmds:
      - task: format
      - task: lint
      - task: test
